//
//  SignUpInteractor.swift
//  Primo
//
//  Created by Jarrett Chen on 12/31/19.
//  Copyright (c) 2019 Jarrett Chen. All rights reserved.
//
//  This file was generated by the UNUM Clean Architecture
//

import UIKit

protocol SignUpBusinessLogic: BaseCleanBusinessLogic {
//  func doSomething(request: SignUp.Something.Request)
}

protocol SignUpDataStore {
  //var name: String { get set }
}

class SignUpInteractor: BaseCleanInteractor, SignUpDataStore {
    
    var presenter: SignUpPresentationLogic?
}

extension SignUpInteractor: SignUpBusinessLogic {
    // MARK: Do something

    func registerUser(email:String?, password:String?) {
        
        if let email = email,
            let password = password {
            
        } else {
            
        }
        
    }
    
//    -(void) registerNew{
//        
//        //Input the loading view
//        self.navigationItem.hidesBackButton=YES;
//        UIView *loadingView = [[UIView alloc]initWithFrame:self.view.frame];
//        loadingView.backgroundColor = [UIColor blackColor];
//        loadingView.alpha=0.5;
//        [self.view addSubview:loadingView];
//
//        UIActivityIndicatorView *loading = [[UIActivityIndicatorView alloc]initWithFrame:CGRectMake(self.view.frame.size.width/2-25, (self.view.frame.size.height)/2, 50, 50)];
//        [self.view addSubview:loading];
//        [loading setActivityIndicatorViewStyle:UIActivityIndicatorViewStyleWhiteLarge];
//        [loading hidesWhenStopped];
//        [loading startAnimating];
//
//
//        //Set Info In Database
//    //    PFUser *newUser = [PFUser user];
//        NSString *lowerEmail = [[_emailField.text lowercaseString] stringByTrimmingCharactersInSet:[NSCharacterSet whitespaceCharacterSet]];
//
//        QueryWebService *query = [[QueryWebService alloc]initWithTable:@"User"];
//        [query selectColumnWhere:@"Email" equalTo:lowerEmail];
//        [query findAllObjectsInRowWithCompletion:^(NSError *error, NSArray *rows) {
//            self.navigationItem.hidesBackButton=NO;
//            [loadingView removeFromSuperview];
//            [loading stopAnimating];
//
//            if (error) {
//                NSLog(@"print error here");
//                return;
//            }
//
//            if (rows.count > 0) {
//                NSLog(@"print error here");
//            }else{
//                self.createParam = [@{@"Email":lowerEmail,@"Password":self.passwordField.text} mutableCopy];
//
//                [self performSegueWithIdentifier:@"profileseg" sender:self];
//
//            }
//        }];
//
//    //    int userNumType = 0;
//    //
//    //    if([self.userType isEqualToString:@"Teacher"]){
//    //        userNumType=0;
//    //    }else{
//    //        userNumType=1;
//    //    }
//    //
//    //    InsertWebService *insertUser = [[InsertWebService alloc]initWithTable:@"User"];
//    //    [insertUser insertObjectInColumnWhere:@"Username" setObjectValue:lowerEmail];
//    //    [insertUser insertObjectInColumnWhere:@"Email" setObjectValue:lowerEmail];
//    //    [insertUser insertObjectInColumnWhere:@"Password" setObjectValue:_passwordField.text];
//    //    [insertUser insertObjectInColumnWhere:@"UserType" setObjectValue:[NSString stringWithFormat:@"%d",userNumType]];
//    //    [insertUser insertObjectInColumnWhere:@"UniversalToken" setObjectValue:[[NSProcessInfo processInfo] globallyUniqueString]];
//    //    [insertUser saveTheUserInDatabaseInBackground:^(NSError *error, id result) {
//    //        if (error) {
//    //            if (error.code == 400) {
//    //                NSLog(@"DUPLICATE!");
//    //            }
//    //        }else{
//    //
//    //
//    //        // Store the data
//    //        NSUserDefaults *defaults = [NSUserDefaults standardUserDefaults];
//    //        [defaults setObject:result[@"UserType"] forKey:@"UserType"];
//    //        [defaults setObject:result[@"Email"] forKey:@"Email"];
//    //        [defaults setObject:result[@"UserId"] forKey:@"UserId"];
//    //            [defaults setObject:result[@"UniversalToken"] forKey:@"UniversalToken"];
//    //        [defaults synchronize];
//    //
//    //        self.navigationItem.hidesBackButton=NO;
//    //        [loadingView removeFromSuperview];
//    //        [loading stopAnimating];
//    //        [loading removeFromSuperview];
//    //
//    //        [self performSegueWithIdentifier:@"profileseg" sender:self];
//    //        }
//    //
//    //    }];
//
//    }
//
    
}
